"use strict";
exports.__esModule = true;
exports.test = exports.hard = exports.normal = exports.easy = void 0;
var easy = { row: 10, col: 10, numberOfMine: 10 };
exports.easy = easy;
var normal = { row: 16, col: 16, numberOfMine: 40 };
exports.normal = normal;
var hard = { row: 16, col: 30, numberOfMine: 99 };
exports.hard = hard;
var test = { row: 5, col: 5, numberOfMine: 3 };
exports.test = test;
